### ISSUE TITLE
[BUG] Preview of image is too large

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#114]
**Describe the bug**
The image preview on the modal in `/dashboard/settings/` is far too long, should display as a circle that is just zoomed in.

**To Reproduce**
1. Go to '/dashboard/settings/`
2. Click on 'change' under "Profile settings"
3. Edit your profile picture to something not square
4. Go back on "Change" under "profile settings"
5. See error

**Expected behavior**
Expected to be a circle

**Screenshots**

![Image](https://github.com/TreyWW/MyFinances/assets/73353716/add12264-5be7-4cc1-b252-84fb2626e450)

**Comment by raizestudio** [comment]
can you please assign this to me ?

**Comment by TreyWW** [comment]
Added commit 41b23ce which fixes a bug related to the top right image.

![image](https://github.com/TreyWW/MyFinances/assets/73353716/1a142d97-f87d-49ce-b159-ecf299a72b06)

Before it would get replaced and the ring would be removed, now keeps the ring + size.
Still got the bug related to the modal, but @SkuliX01 has decided to work on this now due to your inactivity.

Sorry

**Comment by Artal44** [comment]
Is this task still available ?

**Comment by TreyWW** [comment]
> Is this task still available ?

No, sorry @Artal44. This is still being fixed by @SkuliX01.

I may have more bug issues coming out in a about an hour though, I'm just fixing up some code at the moment

Thanks for taking an interest

**Comment by Artal44** [comment]
Oh yeah if you have a new task suited for beginners I would rather take it !
