### ISSUE TITLE
[BUG] Table rows get overridden when adding a new service

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#116]
![Image](https://github.com/TreyWW/MyFinances/assets/73353716/15a6d9af-735e-4b28-a59e-d8758d0e23c5)

/dashboard/invoices/create/

**Comment by namrata18s** [comment]
can you please assign this to me? Thankyou

**Comment by fivecctv117** [comment]
This is from my lastest version
![image](https://github.com/TreyWW/MyFinances/assets/11988182/d05f8885-655e-430f-bbe9-db3118f39ee8)
Can you update the api for services so that we can reproduce the issue ?

**Comment by TreyWW** [comment]
Hi @fivecctv117 
Does the modal not work at all? Could you send any error messages or screenshots of what isn't letting you create any?

Thanks for your interest
