### ISSUE TITLE
[BUG] No dropdown showing when there's only 1 item in invoices list

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#117]
![Image](https://github.com/TreyWW/MyFinances/assets/73353716/30a1c90a-14d5-43ff-a9a9-b7dcbbf3d7d5)

![Image](https://github.com/TreyWW/MyFinances/assets/73353716/98cb1667-bbf6-4cc0-8163-2aa0edf798f2)

Likely down to the `overflow-y-hidden`, we could change to `overflow-y-auto` but I want it to scale down without a scroll bar. Let me know if you'd like more info

**Comment by Jilesh980** [comment]
hi @TreyWW  can i fix this issue, thank you..

**Comment by TreyWW** [comment]
Yeah sure thing. Thank you @Jilesh980

**Comment by TreyWW** [comment]
Fixed by making the card use h-screen. Would be nice to improve the design later, but for now just wanted this bug fixed.
