### ISSUE TITLE
[BUG] salt for hashed password secrets

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#12]
**Describe the bug**
Change `settings.SECRET_KEY` in all of the password reset functions to be something different. As this would break all CODES if the secret key changes. 

Files:
- backend/views/core/passwords/view.py (37)
- backend/views/core/passwords/generate.py (50)
- backend/views/core/passwords/generate.py (82)

**Comment by gulianow** [comment]
Hi, I would like to contribute on this project. Can you assign me on this issue?

**Comment by TreyWW** [comment]
> Hi, I would like to contribute on this project. Can you assign me on this issue?

Hey there,
I'm really sorry but I believe this bug has been resolved, I forgot to update the issue afterwards. The feature does still require tests + a clean up though if you're interested,

I am very sorry, thanks for showing an interest in the project though, I do appreciate it.
If there's another other ideas, feel free to give me a message or comment on other issues. Hopefully this wont happen again, i'll review all current issues and make sure they're up to date.

Thanks 😀
