### ISSUE TITLE
[Enhance] API that allows the downloads from media on permission only

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#123]
At the moment media is accessible from anyone that's logged in, any media. So any account even a blank one can access all of /media. I don't want this. I want all of /media to be blocked permanently for all users.

Instead, I want some sort of API that you can request a file, so lets say in the receipts page, when you "download" your uploaded receipt, it generates you a link.
So lets say: `/api/v1/receipts/download/<receipt_id>` and that returns you
`/cdn/media/<generated_one_time_link>`

Almost like what we do with /invoices/manage_access, where we generate one time urls.

I just want to start planning this, will be needed finished before 0.2.0

**Comment by namrata18s** [comment]
h @TreyWW, can I work on this? thankyou

**Comment by TreyWW** [comment]
Hi @namrata18s, any progress on this issue? Just need a bit of a start to it as this is a high priority issue that needs to be solved before any other releases are made

**Comment by SharonAliyas5573** [comment]
Hey @namrata18s , I wanted to check whether you are actively working on this issue. If you are, I would love to collaborate and assist in any way possible. If not, I am interested in taking it up.

**Comment by TreyWW** [comment]
Hi @SharonAliyas5573,

Yeah you're fine to take it up as @namrata18s seems to be inactive. If she returns you may work together. 

I'll assign you now, thanks for the follow up :)
