### ISSUE TITLE
[Feature RQ] Modal Component

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#15]
We need a modal component in HTML (with tailwind classes) inside of `frontend/templates/components/`

## Preconditions:
Must have a working modal component that can have minimum of `title` and then also some  basic input fields

## Acceptance Criteria:
- Please do task a
- Please do task b

## Definition of Done:
- [ ] All of Acceptance Criteria is complete

**Comment by TreyWW** [comment]
I'll add more info to this soon

**Comment by chavi362** [comment]
@TreyWW , I would like to work on it. 
Please explain me what you want

**Comment by TreyWW** [comment]
> @TreyWW , I would like to work on it. Please explain me what you want

Hey again,
So pretty much we currently have a [modal component](https://github.com/TreyWW/MyFinances/blob/main/frontend/templates/core/components/modal.html) in templates, but we need it to be slightly improved. Needs to have most input types, good margins, easy to add more to it. 

To create a modal at the moment you add 
```
{% include 'core/components/modal.html' with modals=modals %}
```
and then
```
context['modals'] = [] # list of modals
```

Annoyingly I added this modal component without referencing this issue, so it's already nearly complete. 

Reference: [modal html](https://www.ripple-ui.com/docs/components/input) [inputs html ](https://www.ripple-ui.com/docs/components/input)


Thanks

**Comment by TreyWW** [comment]
Added in various commits as it was an urgent feature needed. Apologies @chavi362.

If you'd like to work on any further features, let me know, im sure I can come up with one if there aren't any that fit your needs.
Thanks, and sorry again
