### ISSUE TITLE
[BUG] Close icon not aligned with the logo

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#150]
Logo at the top left of screen when drawer is open doesn't have an aligned cross icon. To debug this I suggest deleting the drawer div (class has "drawer-side") temporary so you can see behind it.

<img width="186" alt="image" src="https://github.com/TreyWW/MyFinances/assets/73353716/cc8ea224-12b0-4331-bc1f-fc00384c0c26">

![image](https://github.com/TreyWW/MyFinances/assets/73353716/dc34a1c6-2012-4275-b4d5-70af515b29a9)

Thanks

**Comment by fivecctv117** [comment]
Hi @TreyWW , I would like to solve this bug, assign me please

**Comment by TreyWW** [comment]
Unassigned due to lack of activity. Feel free to comment back if you would like to work on this bug.

**Comment by muthuruban** [comment]
Assign me..

**Comment by muthuruban** [comment]
Bro.. As i have tried so far I can't able to config Django database correctly, because I am using PyCharm Community version which does not having the edit configuration for Django Server. I have gothrough your installation documentation, but some of the pages are getting 404 error. Is there any other way to setup the environment without affecting the inner code of the settings.py and also the global variables

**Comment by TreyWW** [comment]
Hi @muthuruban, unfortunately pycharm community (like you mentioned) doesn't have Django support. Due to this, I *believe* you will have to follow the other tutorial for "any other IDE". It's suggested to use sqlite especially for development that way you don't need to worry about MySQL. 

Let me know if you need any further help - I should respond a bit faster now I'm awake.

Thanks for looking into our project

**Comment by TreyWW** [comment]
Hi again @muthuruban,

Just a followup message. I've updated the docs with a database section.
I re-read your message and realised that you struggled with the whole environment section. 

Providing that you run django through `py manage.py runserver`, you should be able to just manually edit 
 the `.env` file. (you'll need to move .env.sample to .env first)

Once that's edited you should be able to restart the django application and new env changes should be in.

If this doesn't work let me know as it's probably not your fault and just an issue on our side. Our application hasn't been tested very much on other systems

**Comment by muthuruban** [comment]
Thank you @TreyWW

**Comment by muthuruban** [comment]
@TreyWW Bro I am getting "Can't connect to server on '127.0.0.1' (10061)")

**Comment by muthuruban** [comment]
@TreyWW Thank you for helping me out.. Let me have a clarification, The issue you have raised seems to be no issue there
Here What I see
![Screenshot 2024-01-22 223220](https://github.com/TreyWW/MyFinances/assets/70447939/40410942-ab5c-4ae2-8921-b2979b9bc595)

**Comment by muthuruban** [comment]
Hi @TreyWW Now the Alignment got fixed. So now I don't have access to update the changes. What should I do now?
