### ISSUE TITLE
[IDEA] Forms for manually uploading receipt information

### ISSUE THREAD

**Issue by JoseReino** [TreyWW/MyFinances#151]
Hi I'm a student currently studying CS and came across this project and have a few recommendations regarding the receipt upload feature of the application. I would like to add a feature where users may add receipt information manually into their account.  Essentially, creating forms for the user to fill out like this for each receipt upload similar to this: 
![receipt_exampe](https://github.com/TreyWW/MyFinances/assets/122329580/8d83cf2d-d1bd-4684-b9ce-a5810732fcab)

Users may edit the merchant/store, the date, a purchase category, and amount total for the receipt.
Currently, users can only upload images as receipts and no other information is saved into the account about the receipt. The amounts column in the receipts table is also not editable as of now as far as I know.

## What can this idea add to the project?
- A different way for users to add receipt information into their account
- saving more detailed information for each receipt upload
- adding categories for each receipt which allows for more sorting options

## What areas does this idea come under? 
- Frontend 
- Backend

**Comment by TreyWW** [comment]
That’s a great idea @JoseReino, thank you for letting us know. 
Welcome to the project, it’s great you found us. Would you like someone to be assigned to this idea, leave it open for discussion or work on it yourself?
Whichever option there’s always someone that’ll be around to help, so feel free to ask any time. 

Thanks for the contribution, really appreciate it!
I’ll probably respond in the morning if you reply. Thanks

**Comment by TreyWW** [comment]
This issue is available to anybody, comment if you would like to be assigned. Multiple people welcome too

**Comment by SharonAliyas5573** [comment]
I'm interested in contributing to this issue! It sounds like a great opportunity to collaborate . Please consider assigning this issue to me.

**Comment by TreyWW** [comment]
Hi @SharonAliyas5573, welcome to the project!

Sure thing, you have been assigned now. Let me know if you need any assistance getting started or run into any bugs along the way.

Thanks!
