### ISSUE TITLE
[BUG/PERFORMANCE] Forex Python (currency converter) failing to convert any currencies. Causes long delay.

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#165]
A big bug on the `/dashboard/currency_converter/` page.

When converting currencies (only tested with GBP -> usd/eur), the application hangs for around 10-15 seconds before giving an exception and returning an error to the user. GBP -> GBP conversion still works so the forex api might not be down. Just want someone to debug this and provide further information.

Adding two basic comments to the operation as below, gives the output below.
```py
#convert.py
print("converting currency")
        converted_amt = convert_currency(
            request.POST["from_currency"],
            request.POST["to_currency"],
            amount,
        )
        print(f"finished converting {converted_amt}")
```
```bash
# output
converting currency
```

From the output below we can start to conclude that the error is indeed coming from the currency conversion task. Just needs a bit of debugging and possible fix if you can find an error. Thanks!

References:
- Implemented in #138 primarily by @matthewjuarez1 (feel free to help debug if you're free)
- Backend file is `backend/api/currency_converter/convert.py`
- Fronted did need `hx-post="{% url 'api:currency_converter:convert' %}"` added to the convert button to debug

**Comment by code-master-ajay** [comment]
Hi @TreyWW, can i take this up ?

**Comment by TreyWW** [comment]
That would be great @code-master-ajay, thanks!

**Comment by code-master-ajay** [comment]
Hi @TreyWW, I tried this multiple times with different currency combinations, it did not give any error to me. Can you tell me how can i reproduce the error you are facing or can you share the error log ?

**Comment by TreyWW** [comment]
Oh that's odd. That's the thing I never got any errors (well they were handled so I didn't see the real reason). I could try and reproduce it in a minute, there's a chance it was just the API being down or something. 

I'll let you know when I've tried

**Comment by TreyWW** [comment]
Hi @code-master-ajay,

Apologies for the long delay. I've tested it again today and it's indeed working as you say. Must've been an API outage or something on Forex's end rather than ours. I'll keep testing and re-open this issue if this comes up again.

Thanks for your input
