### ISSUE TITLE
[Feature] Site Settings Page

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#167]
This idea would be to have an admin type page, which any user with Superadmin=True can access, which you could manage Per Site settings. 

Some settings for now could be:
- Toggle user signups (allow login only)

## Definition of Done:
- [ ] Code has been tested with `python manage.py test backend`
- [ ] Implementation has been manually tested and works

**Comment by nishit-prasad** [comment]
New contributor here: can this be assigned to me, please? I'd like to work on this.

**Comment by nishit-prasad** [comment]
Can I get more details on this?
Are you referring to the Account Settings page (that exists) or the page within the URL: http://localhost:8000/admin/?
If I can get more relevant details regarding this one that could help/

**Comment by TreyWW** [comment]
Either. If you can figure out custom options for the existing Django admin page, go ahead.

I thought it would be easier doing a custom page that just update a "site" table. 

Though thinking about it I could put these items in the env file.

I might close this issue later- I'll think about it
