### ISSUE TITLE
[BUG] Multiple Invoices showing under the same ID

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#168]
Bit of an odd bug, probably some test code I accidentally committed in and forgot about, but just came to the project and when creating an invoice the invoice list page shows 4 per invoice. Will debug more later

<img width="949" alt="image" src="https://github.com/TreyWW/MyFinances/assets/73353716/3a865add-9320-4850-ad81-0911789b2c1e">

**Comment by omair-muhammad** [comment]
Hey there, Can I work on this issue?

**Comment by omair-muhammad** [comment]
Hey, Can you mention the steps to reproduce it? Its working fine on my side.
![Screenshot 2024-01-23 at 12 16 01 PM](https://github.com/TreyWW/MyFinances/assets/141236749/3333a578-f3d8-44ad-856b-85b3c0fda9e1)

**Comment by TreyWW** [comment]
Can't reproduce this locally anymore.

Any update @omair-muhammad? If not we can close this issue

**Comment by omair-muhammad** [comment]
I am still able to reproduce this, here are the steps to reproduce:

1. Click on create invoice.
2. Add dummy data in the invoice.
3. Add 2 or more services in the invoice.
4. Create invoice with those services.

If you add 2 services then 2 invoices would be created with same IDs, names etc. You can arrange a meeting or can share your contact to discuss this further.

**Comment by TreyWW** [comment]
Hi @omair-muhammad,

Thanks for the update, glad you managed to reproduce it.

The issue does seem to come from this line:
https://github.com/TreyWW/MyFinances/blob/c867b38faa888e1d5617ae8babb96053f77e6646/backend/api/invoices/fetch.py#L42

Probably something to do with the annotation or something like that.
What contact method would be easiest? Just let me know!

Thanks again

**Comment by omair-muhammad** [comment]
Sure, I will get back to you on this.
