### ISSUE TITLE
[Enhance] Add HTMX to invoices/edit submittion with messages

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#187]
## What areas does this enhancement come under? 
- Backend 
- Test Cases

**Comment by BuerJeanMaxime** [comment]
In my last jobs, I had to use Django and some htmx features (this my new personnal profile). I can try to help you out if you want

**Comment by TreyWW** [comment]
Sure thing @BuerJeanMaxime, let me know if you need any help or have any questions. Make a PR when youre done :)

**Comment by BuerJeanMaxime** [comment]
I've created a fork, but I can't get the code. I have even created a new ssh key. But, either with http or ssh, I've got this error
![image](https://github.com/TreyWW/MyFinances/assets/160487743/c98df67b-d848-44b4-a7c1-08b6c4ad17b7)

**Comment by BuerJeanMaxime** [comment]
Nevermind, I did it. Windows sometimes... (Can't be link because of me compagny computer)

**Comment by BuerJeanMaxime** [comment]
Quick question, do you want me to use htmx as maxima or do you want some part of the html page to have htmx

**Comment by TreyWW** [comment]
> Quick question, do you want me to use htmx as maxima or do you want some part of the html page to have htmx

What do you mean by `as maxima`? You can view our other pages to see how htmx is implemented

**Comment by BuerJeanMaxime** [comment]
Thanks, I'll envistgate that today

**Comment by BuerJeanMaxime** [comment]
I've made a few changes, but I can't test it. After poetry is installed, I continue with your tutorial, but he said to me that "myfinances" folder/app is not found. I've created a new empty fodler, but it doesn't change anything.
There a screen of what I had : 
![error](https://github.com/TreyWW/MyFinances/assets/160487743/94a7237c-2198-440c-8c61-737eb5170189)
Thanks for your response ;)

**Comment by TreyWW** [comment]
Hey @BuerJeanMaxime, I'm so sorry for not replying sooner - I completely missed this message.

You can ignore this warning as it doesn't actually do anything bad the app should still work fine. As for not being able to test do you get an error with django when running `py manage.py test`?

Maybe you could try `poetry install --no-root --with dev,django` let me know how that goes!

Thanks for your patience, apologies for missing the message

**Comment by Nout-Prins** [comment]
Hey, I was wondering if I could have a shot at this issue. I just finished installing the app and running the tests and it works.

**Comment by TreyWW** [comment]
Hi @Nout-Prins,
This issue has already been assigned and it was my fault that it didn't get worked on so I think it's only fair to let @BuerJeanMaxime complete it if they are still interested.

If they don't reply for a few days I can unassign them and you can step up. There's a few open issues though that you could work on, or even take a look at the app and come up with some ideas on making it better!
