### ISSUE TITLE
[Enhance] Update test cases to work with both organizations + normal individual accounts

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#188]
At the moment our tests only cover individual accounts. But now I'm working on #87 (teams) the ability to log into individual accounts and organization accounts is now a thing. This means we will struggle to find bugs and in general will be a mess.

Would be nice to get some tests in to also cover organization ability to do all of the same things as users. Also test cases for switching to organization and back to user, etc etc.

Some example test cases:
- Creating an invoice, make sure it creates on the account of the logged in user / logged in company
- Viewing all invoices, make sure you only view your logged in user/companies invoices
- Make sure users cannot create invoices under teams they don't belong in (member of or leader of)
- etc etc

Feel free to leave a comment if you would like to work on this. Make sure to ask for help if you would like to work on this but don't know how to start! :)

**Comment by TreyWW** [comment]
Hi @shwetabh-23,
Welcome to our project!

So recently I made a start to teams functionality, which allows users to act on behalf of a team account rather than just their own.

So a lot of our current tests need to be duplicated, but for teams aswell as users.

I'll take you through one test case to help get you started on an invoice test.
```py
# (Before i describe, i've created some example helper methods for ViewTestCase class of handler.py in tests)
def setUp(self):
    self.log_in_user = User.objects.create_user(
        username="user@example.com", password="user", email="user@example.com"
    )
    self.created_team = Team.objects.create(
        name="Testing", leader=self.log_in_user
    )
    self.mock_images = []
    self.htmx_headers = {"HTTP_HX-Request": "true"}

def login_to_team(self):
    self.login_user()
    self.log_in_user.logged_in_as_team = self.created_team
```

`tests/views/test_invoices.py`

For example we have a test case

```py
def test_invoices_view_200_for_authenticated_users(self):
    self.login_user()
    response = self.client.get(self._invoices_dashboard_url)
    self.assertEqual(response.status_code, 200)
```

But we could add support for both individuals and teams like this:

```py
def test_invoices_view_200_for_authenticated_users(self):
    self.login_user()
    # test individual account
    response = self.client.get(self._invoices_dashboard_url)
    self.assertEqual(response.status_code, 200)
    # test with team acc
    self.login_to_team()
    response = self.client.get(self._invoices_dashboard_url)
    self.assertEqual(response.status_code, 200)
```

This mainly applies to test cases like InvoicesCreateTestCase -> InvoicesCreateTestCase. Where you can assertEqual that  invoice.organization is filled instead of invoice.user


How you decide to go about this is up to you, whether you add more helper methods, write repeated code, it's up to you. Tests aren't about complexity but just about trying to get everything in, however possible.

Some tests we don't have, such as checking if invoices are loaded, but it's up to you if you want to add any tests like that or just add onto our existing tests.


As for getting setup with the project you can follow [our setup guide](https://myfinances.strelix.org/#/getting-setup/).

Let me know if you need any additional help, sorry about the delay, I'm always down to help out!

**Comment by NikolaSL00** [comment]
Hey, I want to contribute, but I have difficulties on setting up the project

**Comment by TreyWW** [comment]
Hey @NikolaSL00
Sorry to hear that, what part are you stuck at? We have some docs though still need to update to make a little better. 

Let me know what youre stuck at

**Comment by SBMOYO** [comment]
Hey, I want to contribute but am facing a problem when I run poetry install. Please can you help!

**Comment by TreyWW** [comment]
Sure thing @SBMOYO,
Whats the error that you've come across?

**Comment by SBMOYO** [comment]
the error is 

'The current project could not be installed: No file/folder found for package myfinances'

am running poetry install while am in side Myfinances project directory. when I run the command, its installing all the other stuff like django, pillow etc after that this error occurs

**Comment by SBMOYO** [comment]
when I run py manage.py migrate it's running successfully. Not sure why that error was showing

**Comment by TreyWW** [comment]
Yeah that's a little odd. You should be able to just ignore the error then. Sometimes i get poetry warnings too but still installs all decencies so 🤷

**Comment by SBMOYO** [comment]
@TreyWW, I would like to inquire about the process for creating invoices within Teams. Specifically, I am interested in understanding whether this responsibility lies solely with the team leader or if any team member has the authority to generate invoices.

**Comment by TreyWW** [comment]
Hey @SBMOYO,

At the moment we only check if the user has selected the a team as verification, so they _only need to be a member_. We will in the future work out a permission system though.

**Comment by TreyWW** [comment]
Hey @SBMOYO,

Just looked over some of our views and realised some just require to be logged_in_as_team and some check if it's the invoice.user (meaning the owner) is, for example `if not invoice.user.logged_in_as_team and invoice.user != request.user` for invoice deletion.
