### ISSUE TITLE
[BUG] Drop external CDNs

### ISSUE THREAD

**Issue by wnm210** [TreyWW/MyFinances#190]
**Describe the bug**
The front-end of MyFinances depends on non-free and third-party domains delivering possibly unwanted Javascript to the browser. This should be resolved, and the app should be independent.

External CDNs can block people from accessing resources you build upon, and after that, some of your users won't be able to use MyFinances. And everything without your consent. Furthermore, from time to time, CDNs are offline, causing your project to be down too! Not mentioning that you waive your privacy and that they can inject anything into your website.

CDNs cannot "speed up" your page. The best way to load resources is to do that from the website itself, not depending on anything.

Fine, you can use CDNs with a fallback to local resources, but what for? You gain nothing. Maybe there is less traffic on your network. But is it important? Not really; most of the ISPs provide unlimited usage.

Cross-site file caching is not a thing anymore, so using CDNs is pointless. More downsides than actual benefits.

**To Reproduce**
1. Go to live preview
2. Open NoScript extension

**Expected behavior**
Please serve resources locally. It's better for privacy and stability of the application.

**Screenshots**
![image](https://github.com/TreyWW/MyFinances/assets/49320100/6532fe6b-f47c-4a27-8693-60f280bd1737)

**Comment by wnm210** [comment]
Forgot to change the title. As always. 💀

**Comment by TreyWW** [comment]
I have added an option to toggle between CDN or Local. Though, _as expected_, drops the page performance from a 98/100 to 73/100 even with a compressed, production build of the bundle.

CDNs don't have much downtime if any, as they're built on top of very good architecture that's literally MADE to be redundant.

> unwanted Javascript
> privacy and stability of the application

As for the security concerns, they're not applicable if we provide hash values for the CDN urls - such as javascript `integrity`. Which would be added to all scripts in production. Though having manual CDN urls may take longer to update if dependabot/etc doesn't automatically pick them up it's still worth while.

The options for ALL javascript packages (no exceptions) going forward will be either:
- NPM Packages locally installed and bundled into github _(new default)_
- Public CDNs (e.g. `code.jquery.com` or `unpkg.com`)
- Private CDNs (e.g. cdn.mysite.com)

The approach that the production hosted version of MyFinances will use will likely be our Private CDN. But locally downloaded copies of the project will default to using a Bundled version of NPM packages.

I hope this satisfies your needs for the project :)

Let me know if this NPM approach wasn't your idea of an alternative @wnm210

**Comment by wnm210** [comment]
Everything sometimes has a downtime. CDNs no longer give you the benefit of faster loading times, as browsers stopped supporting cross-site caching. The performance "drops", but how is it measured? It is a bit faster because some servers are closer to you than others. Although, is it worth it? You give away your privacy just to load the site faster for some users. And the site will load faster by maybe 0.25s. Not mentioning that it only works when they visit it for the first time.

It's a huge disadvantage for users of NoScript when they have to allow Javascript from third parties.

The best would be to ditch external resources, but if you really care about 250 ms during the first load, then sure, keep it. But for increased privacy, the setting should be disabled by default.

**Comment by TreyWW** [comment]
> You give away your privacy

How come? All you're doing is fetching a file

> It's a huge disadvantage for users of NoScript when they have to allow Javascript from third parties.
Don't you have to do that for all sites, that's the whole point of NoScript is to allow sites you trust?

> the setting should be disabled by default

I did mention that i just added this, yes

**Comment by wnm210** [comment]
> How come? All you're doing is fetching a file

Exactly, and by that you provide your data to a third party! Your browser language, operating system, browser version, the page you visited. That's how they track you on the internet. By fingerprinting.

> Don't you have to do that for all sites, that's the whole point of NoScript is to allow sites you trust?

I trust sites I visit often, not third parties and trackers. And CDNs can't be trusted.

> I did mention that i just added this, yes

And CDNs are **disabled** by default?
