### ISSUE TITLE
[Enhance] Scale invoice better

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#210]
There are lots of issues with invoice scaling at the moment, I'd appreciate if somebody could help fix some of them up.

> Note: The invoice file is `frontend/templates/pages/invoices/view/invoice.html`

First issue is that invoices have a lot of blank space as they scale based on screen size, but it should scale based on **content** size. So invoices don't need to be the height of screen. E.g. i've added some images below to help picture this.

![image](https://github.com/TreyWW/MyFinances/assets/73353716/0c69701a-b2da-4e62-a5e2-35ad457d381d)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/2d59ac7f-2f8b-4953-8e9f-9336d4d457ea)

The next issue is that on the print screen a second page is created, and it's just a bit of a mess.

![image](https://github.com/TreyWW/MyFinances/assets/73353716/ff7157fd-1b42-44e2-a6e5-ecc63d9a1b71)

But it does scale quite well if there are too many items on one page, so make sure that it doesnt effect that. (some margin at the top would be ideal though)

![image](https://github.com/TreyWW/MyFinances/assets/73353716/e4d0cbac-74e9-4346-b437-394ec0052e51)

**Comment by v-j-jpg** [comment]
Hi @TreyWW, I think I can help with this issue. Can I get assigned to this bug if it's still not fixed?

**Comment by kryptokun** [comment]
Can I get on this issue as well? I haven't seen any updates on it.

**Comment by TreyWW** [comment]
Fixed in #262 (thank you @wnm210 for reminding me)
