### ISSUE TITLE
feature: Client main contact method

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#223]
A "main contact method" field to client objects

## What can this idea add to the project?
- Allow users to see how they are mainly interacting with their customers (via email, phone, texts, messenger, etc etc)
- Also can be integrated onto invoices at a later point if the user wants to add a "How can I get help" type section on the invoice

## What areas does this idea come under? 
- Frontend
- Backend + Models

Open to all, it's low priority so I won't be working on it any time soon, so leave a comment if you'd like to work on it!

**Comment by Krishn1412** [comment]
can you please assign this issue to me?

**Comment by TreyWW** [comment]
Sure thing @Krishn1412 

Please let us know if you aren't able to complete the task as we don't like inactive issues if someone else can be working on it. Otherwise just let us know if you have any issues

**Comment by Krishn1412** [comment]
Sure,
Thanks!

**Comment by TreyWW** [comment]
Has there been any progress @Krishn1412?

**Comment by marvinl803** [comment]
Hi, can you please assign me this issue.
