### ISSUE TITLE
[IDEA] Enhance issue template

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#23]
I'd like somebody to create an "ENHANCE" template, based on the other .github/issue_templates, that gives the "enhance" label and [Enhance] or [ENHANCE] prefix.

**Comment by TreyWW** [comment]
Welcome along, thanks for contributing 👋🏽

**Comment by chavi362** [comment]
Thank you for assigning me.
I made a pull request. Please merge this.
Have a great day!

**Comment by TreyWW** [comment]
Thanks, merged now. Apologies for the wait. Appreciate your contribution, and welcome to the project.

Have a good day 😄

**Comment by TreyWW** [comment]
@all-contributors please add @chavi362 doc
