### ISSUE TITLE
bug: Details dont get pre-filled using the "Update FROM info" modal on EDIT

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#232]
### What version of MyFinances are you currently using?

v0.2.1 (latest)

### Describe the bug

Using the edit modal the details never get pre-filled (value) from DB

**Comment by TreyWW** [comment]
![image](https://github.com/TreyWW/MyFinances/assets/73353716/5dccb24e-53a3-4616-aaed-96f088be2c88)

**Comment by introkun** [comment]
I'm on it
