### ISSUE TITLE
bug: Wiki is outdated to setup project with other IDE

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#236]
### What version of MyFinances are you currently using?

v0.2.1

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

https://github.com/TreyWW/MyFinances/wiki/Setting-up-Django-with-Other

I'd suggest to add:
```
pip3 install poetry
poetry install
```

**Comment by TreyWW** [comment]
Apologies, I forgot to remove the wiki tab when I added our main documentation. I'll remove it now :)

**Comment by introkun** [comment]
Thank you! I've just started setting up the project :)

**Comment by TreyWW** [comment]
Cool, let me know if you come across any issues. Our "new docs" are also now outdated so apologies if you come across any issues. Feel free to create an issue or respond here if you face any more. 

Good luck :)
