### ISSUE TITLE
bug: Broken Black Linter Github badge in the README

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#247]
### What version of MyFinances are you currently using?

v0.2.1

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

Broken Black Linter Github badge in the README
<img width="412" alt="image" src="https://github.com/TreyWW/MyFinances/assets/61635/5f48e8c3-4eea-48da-84d0-ef6d9c4a4347">

**Comment by introkun** [comment]
Fixed 
<img width="394" alt="image" src="https://github.com/TreyWW/MyFinances/assets/61635/267bab85-b210-468b-bf22-159bd00a1d60">

**Comment by TreyWW** [comment]
Merged in #247
