### ISSUE TITLE
bug: "Using local settings" logged twice in console during the project start

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#250]
### What version of MyFinances are you currently using?

v0.2.1

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

```
❯ python3 ./manage.py runserver
[BACKEND] Using local settings
[BACKEND] Using postgres database: myfinances_development
[BACKEND] Using local settings
[BACKEND] Using postgres database: myfinances_development
```

**Comment by TreyWW** [comment]
I believe this is just due to djangos local server, when you run with `runserver` django starts two servers, the main one and the auto restart one. I was wondering this before too. If this is incorrect feel free to let me know.

**Comment by introkun** [comment]
I have another django project, but I never saw this. I think it's an issue.

**Comment by TreyWW** [comment]
Oh right, I'll take a look into it tomorrow, thanks for pointing it out

**Comment by TreyWW** [comment]
When looking into this a few people have mentioned that the auto-reloader django uses with runserver is what caused their issues with duplicate logs. I believe this is the issue. It's just that we print every time the settings file gets called, maybe your other project doesn't print at the top?

**Comment by introkun** [comment]
Yes, my other project doesn't print from the settings.py. I checked by adding print and I see the same behaviour. Not an issue, closing.
