### ISSUE TITLE
bug: Not able to view invoice with 0 amount

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#259]
### What version of MyFinances are you currently using?

v0.2.1

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

HTTP error 500
<img width="892" alt="image" src="https://github.com/TreyWW/MyFinances/assets/61635/0e705236-d50f-48c9-a793-334f87abf0ec">

**Comment by TreyWW** [comment]
Oh yeah this is the change I made yesterday with discounts, I knew it would break stuff. I'll fix it tomorrow. Thanks for pointing it out
