### ISSUE TITLE
bug: manage.py makemigrations shouldn't be a part of production execution

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#274]
### What version of MyFinances are you currently using?

v0.2.1

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

python3 manage.py makemigrations shouldn't be a part of production execution
File: infrastructure/backend/scripts/entrypoint.sh
`python3 manage.py makemigrations --no-input && ...`

**Comment by TreyWW** [comment]
Oh yeah that's a good point, never really thought about that as it's never actually been used, maybe we should put it somewhere in GH Actions just to make sure it's never forgotten?

**Comment by introkun** [comment]
I didn't get. We just should remove python3 manage.py makemigrations --no-input from the entrypoint.sh.
makemigrations is called by developers manually...

**Comment by TreyWW** [comment]
But what I'm saying is that if it's forgotten to run by someone and gets accidentally merged in, it'll break everyone's app. Maybe a precommit hook or something instead?

**Comment by introkun** [comment]
Doesn't work for VS Code:
```
Check django migrations..................................................Failed
- hook id: pre-commit-django-migrations
- exit code: 1

Executable `./manage.py` is not executable
```
And I see warning for black:
```
2024-04-05 23:15:44.169 [info] [WARNING] Unexpected key(s) present on https://github.com/psf/black: entry
black....................................................................Passed
```

**Comment by TreyWW** [comment]
Being held by #300
