### ISSUE TITLE
Invoices table not aligning well after fillter change [bug] 

### ISSUE THREAD

**Issue by v-j-jpg** [TreyWW/MyFinances#276]
### What version of MyFinances are you currently using?

Main

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

On http://127.0.0.1:8000/dashboard/invoices/ page after the fillter is applied the table isn't scaling properly (examples below). This creates an unexpected layout shift.
<img width="1515" alt="Screenshot 2024-04-02 at 14 27 23" src="https://github.com/TreyWW/MyFinances/assets/58274307/541700ef-db3e-4fd1-aedc-d83d6cb2d6fb">
<img width="1523" alt="Screenshot 2024-04-02 at 14 26 45" src="https://github.com/TreyWW/MyFinances/assets/58274307/34f385b8-ddd6-482a-a435-290abe2f87b5">
<img width="1519" alt="Screenshot 2024-04-02 at 14 26 32" src="https://github.com/TreyWW/MyFinances/assets/58274307/f97ea86f-526e-431b-b078-5587f0324471">

**Comment by TreyWW** [comment]
Yeah I agree, I'm rubbish with the frontend and this has been an issue since day one of the invoice table. I'm not sure how to scale the table nicely so that it looks like image 2 all the time. I'm happy for someone to work on this though!
