### ISSUE TITLE
bug: Invoice add service scaling issue for mobile devices

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#297]
### What version of MyFinances are you currently using?

v0.3.0 (latest)

### What device type are you currently facing the issue on?

Mobile

### Describe the bug

(search should scale down, and button should be underneath)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/66e20676-a548-4c14-ad7b-077a509777f6)
(search should scale down and button should be beside)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/d99a0f11-2725-4920-8463-e49f592108da)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/74834205-570f-4888-86b2-71bbcb56ee71)

(too large of a plus button)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/61839a90-2211-4e51-961c-8876c61251b3)

**Comment by spalominor** [comment]
Hey, I can work on this?

**Comment by TreyWW** [comment]
Sure thing @spalominor

**Comment by spalominor** [comment]
@TreyWW what via to contact you for any question?

**Comment by TreyWW** [comment]
Discord feels the most "real time" and I'll probably respond fastest on there. It's listed on [the docs](https://docs.strelix.org/MyFinances/)

**Comment by spalominor** [comment]
I'm sorry @TreyWW, the link doesn't work, have you one other?

**Comment by TreyWW** [comment]
So sorry about that, I'll get that fixed in the morning. Try this one https://discord.gg/YDQq2uc2ap
