### ISSUE TITLE
bug: Invoices sorting issues

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#298]
### What version of MyFinances are you currently using?

v0.3.0

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

Sorting on the Invoices page works only in one way (Asc or Desc). Not able to click on the sorting control again to reverse sorting.

**Comment by introkun** [comment]
<img width="398" alt="image" src="https://github.com/TreyWW/MyFinances/assets/61635/89a77aa5-9794-48c5-95f5-e55cf403dcf8">
Clicking again on Date/Payment Status/Date does not change the sort order.

**Comment by spalominor** [comment]
I want to work on this...
