### ISSUE TITLE
bug: Misleading invoices "Date" column name

### ISSUE THREAD

**Issue by introkun** [TreyWW/MyFinances#302]
### What version of MyFinances are you currently using?

v0.3.0

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

There's a "Date" column in the Invoices window.
As of now, it's not clear if it's "Due Date" or "Invoice Date". In reality, it's a "Due Date".
Let's rename the column.
<img width="766" alt="image" src="https://github.com/TreyWW/MyFinances/assets/61635/981a5cab-5db9-42e4-8e2a-560913c17bcf">

**Comment by spalominor** [comment]
🆗

**Comment by Domejko** [comment]
I've fixed it and will send PR now.
