### ISSUE TITLE
bug: Favicon infinite redirect

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#311]
### What version of MyFinances are you currently using?

v0.3.0 (latest)

### Describe the bug

![image](https://github.com/TreyWW/MyFinances/assets/73353716/f48d3ad3-18f1-4a5b-80f0-65d7dbb35cff)

Due to the redirect favicon we get an infinite redirect to the endpoint if there's any sort of error.

This needs more debugging. Open to anyone :)

**Comment by introkun** [comment]
fixed in #312

**Comment by introkun** [comment]
<img width="945" alt="image" src="https://github.com/TreyWW/MyFinances/assets/61635/b52a2792-fb2a-40cd-a2cb-0c42e1c4411c">
