### ISSUE TITLE
bug: Users name + selected profile isn't shown on first load

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#320]
### What version of MyFinances are you currently using?

latest

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

![image](https://github.com/TreyWW/MyFinances/assets/73353716/40e8471e-fc14-4bbf-90a7-95576f0c99ac)

No team / organization text on new deployment (not yet debugged)

**Comment by TreyWW** [comment]
Hm when going on another page it loaded again. Still needs to be further looked into

**Comment by nayelimdejesus** [comment]
Hi, I would like to work on this issue.

**Comment by TreyWW** [comment]
Hi @nayelimdejesus, sorry I missed the message, would you still like to work on this issue?

**Comment by nayelimdejesus** [comment]
Yes

Respectfully,
Nayeli M. De Jesus

**Comment by nayelimdejesus** [comment]
Hey, I'm new to open source and I'm looking into this issue, and I haven't seen any problems with the username loading. Are you able to elaborate on this issue? Thank you.

**Comment by TreyWW** [comment]
Hey, thanks for replying. Yeah this was an odd bug, it happens only every so often. It occurred to me on a brand new deployment with a blank database. I can try setting up the project a few more times to try and get it to bug again

**Comment by TreyWW** [comment]
Moved to #413
