### ISSUE TITLE
bug: Receipt cost input to accept decimal rather than just integer

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#329]
### Discussed in https://github.com/TreyWW/MyFinances/discussions/328

<div type='discussions-op-text'>

<sup>Originally posted by **ryansurf** April 13, 2024</sup>
At the moment, the receipt cost input only accepts integers(4, 5, 6, etc). I think it should accept up to two decimals for accuracy 

![Capture](https://github.com/TreyWW/MyFinances/assets/94500732/fd32a8f4-89c6-484c-88d6-b10b684fcbb0)
</div>

**Comment by esass10** [comment]
Hi! Can you please assign this issue to me?

**Comment by TreyWW** [comment]
Sure thing @esass10, apologies for the delay

**Comment by TreyWW** [comment]
Fixed in #341 / #331. Apologies
