### ISSUE TITLE
bug: Service quotas page looks rubbish on mobile

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#332]
### What version of MyFinances are you currently using?

V0.3.0 Latest

### What device type are you currently facing the issue on?

Mobile

### Describe the bug

![IMG_0974](https://github.com/TreyWW/MyFinances/assets/73353716/283232fb-9e29-4e30-8f79-1dc24261e494)

**Comment by ryansurf** [comment]
I've got this one. What do you think about adding some hover effects too?

**Comment by TreyWW** [comment]
Fixed in #339
