### ISSUE TITLE
bug: Login page broken on mobile 

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#333]
### What version of MyFinances are you currently using?

V0.3.0 latest

### What device type are you currently facing the issue on?

Mobile

### Describe the bug

![IMG_0973](https://github.com/TreyWW/MyFinances/assets/73353716/35a89584-40a9-4112-acf6-c5cc16999bb4)

also cannot use the text box or button unless you turn the phone around

**Comment by SilentSobs** [comment]
I checked It's working fine.

**Comment by TreyWW** [comment]
The bug still persists @SilentSobs. Not reproducible on browser but is still on mobile as reported (on Iphone 11)

**Comment by CKsabari2001** [comment]
@SilentSobs are you still working on this one? or Can I take this ?

**Comment by TreyWW** [comment]
Hey @CKsabari2001, they never got assigned so this issue is still available

**Comment by TreyWW** [comment]
If you have a look at the docs @CKsabari2001 it shows how to setup. There's a sample env file in the root directory

**Comment by CKsabari2001** [comment]
@TreyWW I am new to this Repo and am a Frontend developer so, I am new to Phyton and Django too. 
I went through the docs I installed Python on my local machine 
I created a sample env like mentioned in docs 
but while running this line I got an error in my terminal "python manage.py migrate"

![Screenshot 2024-04-18 180931](https://github.com/TreyWW/MyFinances/assets/110533554/b38762d8-5fec-4cab-9a70-8033f95e65d0)

**Comment by TreyWW** [comment]
Ah okay, could you try `poetry add django_ratelimit` and then `poetry install` again. Apologies for that

**Comment by CKsabari2001** [comment]
after that, we need to run this command uh? "python manage.py migrate"

**Comment by TreyWW** [comment]
Yeah

**Comment by TreyWW** [comment]
What was the output of the previous command? (poetry add django_ratelimit)?

**Comment by CKsabari2001** [comment]
![image](https://github.com/TreyWW/MyFinances/assets/110533554/85a6369f-9f64-45ed-8c46-fb5fabae8ab0)

**Comment by TreyWW** [comment]
I wrote a docs page for this today, hasn't been commited yet though:

# Already installed

The error where `poetry install` says "Skipped for the following reason: Already installed" but `pip freeze` shows that these
clearly aren't installed, you may need to configure your poetry environment to use the local ./venv/ instead of a global one.

First, make sure you aren't in a venv (`deactivate`). If there isn't a /venv/ folder inside of the project, you'll need to
create one with `python -m venv ./venv/`. Now activate it. `./venv/Scripts/activate`.

After you have a venv and it's activated you can run these poetry config commands:

```shell
poetry config virtualenvs.in-project true

poetry config virtualenvs.path ./venv/

poetry install
```

And this time they should all be correctly installed!

**Comment by CKsabari2001** [comment]
![image](https://github.com/TreyWW/MyFinances/assets/110533554/ab73dec0-fd3a-4008-ab25-b4be1bfb97dd)

**Comment by CKsabari2001** [comment]
Now it's working but I am facing another issue while creating an admin ACC I can't able to set the password 

![image](https://github.com/TreyWW/MyFinances/assets/110533554/fe3cdc5a-3c5a-4a7c-b2ef-ada0f37fc321)

**Comment by CKsabari2001** [comment]
but can't able to type anything in the password field

**Comment by TreyWW** [comment]
🤷🏽 works for me. That's just default django behaviour. If it doesn't work you'll have to make a bug request with the official django repository, that's nothing to do with us.

It's probably your terminal though, try in command prompt / any other terminal. If you're using the new from PyCharm that may be causing it.
