### ISSUE TITLE
bug: Share Invoice button shouldn't be visible when not logged in

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#337]
### What version of MyFinances are you currently using?

latest

### Describe the bug

On the invoice share `/invoice/<invoice_id>` the "share invoice" button is still there but just asks you to login, maybe should be disabled or removed for non-logged in/ no-perms users

**Comment by glizondo** [comment]
Hello @TreyWW I would like to help out with this issue. I haven't worked with Django but I got to play a lot with Python, it would be nice to contribute to this. Thanks

**Comment by TreyWW** [comment]
Sure thing! We have a setup guide on the [docs](https://docs.strelix.org/MyFinances/) they aren't the best but should help you get setup.

Feel free to let me know if you need any help, thanks for the interest though!

**Comment by glizondo** [comment]
Awesome. Thanks!
