### ISSUE TITLE
bug: run_tests.yml CI run tests only on Python 3.12

### ISSUE THREAD

**Issue by Domejko** [TreyWW/MyFinances#360]
### What version of MyFinances are you currently using?

v0.4.5

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

Tests that are run by `run_tests.yml` are all run only on `python 3.12` and `django` version specified in requirements. Reason for that is running tests through container setup by `infrastructure/backend/Dockerfile` which is build on `python:3.12-alpine`.

Solution for that can be adding another job to test code with different `python` and `django` versions in the same file or creating separate `.yml` files, one for code testing and one for docker build.

@TreyWW  you can assign this to me. We can discuss options and I will fix that issue.

**Comment by TreyWW** [comment]
Hey @Domejko 

Im thinking of maybe soon only allowing py 3.12 anyways, because I'm pretty sure some of the type hints and fstring syntax that we use isn't supported in the older versions. Especially the type hints only got natively supported in 3.12. I've not actually tested properly, but from what I can remember trying to run on 3.9 failed on my laptop hence why I had to update to 3.12

Some confirmation would be nice though

**Comment by Domejko** [comment]
Yes 3.9 would be too far back but versions 3.10, 3.11 will be working since my linux is setup with those and I haven't yet encounter any issues. I did check now on updates in v3.12 and at the moment I haven't seen anywhere throughout the code that `type statements` or `TypedDict` for **kwargs that would be causing issues with older versions. Also in case when for example version 3.10 would be outdated it will be just a matter of removing that version from CI. It's not something that would happen every week so it wouldn't be troublesome.

If decision would be made to allow only v3.12 then we can cleanup `run_tests.yml` to cut the actions time and avoid doing unnecessary steps in CI. But if we will still want to test other versions then it's a matter of deciding should docker and tests be kept in one file or should we split them to separate files. In that case I would suggest splitting them for better readability.

**Comment by TreyWW** [comment]
Would it not be possible to use matrix to change python version? I've seen it used in a ton of apps, there shouldn't need to be extra files

**Comment by Domejko** [comment]
Yes matrix will be used, What I meant is to have 2 files, one for running docker files from `infrastructure/backend/` with out matrix etc, having only necessary steps for running `Dockerfile`. Second file with regular setup using matrix for python and django to run regular tests.

Tomorrow I will look more closely for some elegant solution.
