### ISSUE TITLE
bug: Logging in without HTMX gives error

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#376]
### What version of MyFinances are you currently using?

latest

### Describe the bug

<img width="483" alt="image" src="https://github.com/TreyWW/MyFinances/assets/73353716/70b4d64f-8fd4-4c60-a627-4ba756dc7e4f">

If for whatever reason loading JS doesn't work, HTMX falls back to a post request, which doesn't work atm

**Comment by Domejko** [comment]
@TreyWW  could you provide some example how to reproduce that error ?

**Comment by TreyWW** [comment]
Try and login with no frontend JS code or browser allow no JavaScript
