### ISSUE TITLE
bug: No message for the user when trying to delete not existing Invoice

### ISSUE THREAD

**Issue by Domejko** [TreyWW/MyFinances#377]
### What version of MyFinances are you currently using?

v0.3.0

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

When you have invoices opened on 2 different tabs and on one of them you will delete Invoice and then you will try to delete the same Invoice on the 2nd tab you will get thrown into infinite loop where you constantly get asked do you want to delete that invoice where nothing will happen and you don't get any message that "Invoice not found".

**Comment by TreyWW** [comment]
Thanks for the bug report @Domejko! I can work on this on the weekend unless you'd like to work on it - just give me a ping.
