### ISSUE TITLE
bug: Create Invoice Form Required Fields

### ISSUE THREAD

**Issue by derrickpriebe** [TreyWW/MyFinances#388]
### What version of MyFinances are you currently using?

v0.4.5

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

In the “Create Invoice” form, the denotation for required and optional fields is not consistent with the rest of the creation forms. It is denoted by two sections called “Required Fields” and “Optional Fields” when the specific fields should have red astericks and the form sections would not be applicable and can be deleted.

**Comment by TreyWW** [comment]
Thank you for the bug report! I'll work on this now

**Comment by TreyWW** [comment]
Hmm, maybe instead of adding required to every field if I added a red asterisk to each "section" would that look better maybe?
![image](https://github.com/TreyWW/MyFinances/assets/73353716/91c4ff8b-c1ae-436b-87f7-4f452ab8b3bc)
