### ISSUE TITLE
rewrite: quota system

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#403]
The quota system feels a bit clunky and everything is so rubbishly thought out. If anyone would like to help me refactor it and fully re-think it's architecture please add a comment!

**Comment by Domejko** [comment]
I would like to participate. What's the main idea for the payments ? You think of having like let say 3 - 4 account tiers and just that, or maybe with a possibility to by additional quotas ? Some kind of free trials or just basic free account with small quota usage ? Either way it's good to think of now on storing and checking users IP addresses as well does user use VPN.

As for quota architecture it self after brief looking through the code I think we should implement check for the quota usage as a middleware to avoid repetitive checks through out the code.

**Comment by TreyWW** [comment]
Incredible idea for the middleware. I'll have a think about all the things tomorrow and mind map it. But from off the top of my head payments may go like this:

- Free trial/demo acc: small limit on some features, limit of 0 for features that may cost too much
- pay-for-usage for anything else. So quotas will be fairly high on default, and if they need additional quotas (e.g a big business) we play the cloud flare game and they speak to us separately and we work out a plan with them. And give them custom payment options with custom quotas and cheaper rates for pay for usage. 

If you'd like to talk more about this feel free to take it to the discord channel, I always miss GitHub notifications but always seem to catch discord ones. 

Appreciate the interest!

**Comment by TreyWW** [comment]
Closing as we've moved to usage based pricing we no longer need these quotas as we had before. May look into again in the future if we need it.
