### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#409]
Soon we'll want some form of Public API. This allows customers to, if they wish, expand on our frontend/add integrations, to make the most out of our project. We will use django-rest-framework.

So we'll want two forms of "APIs".

1. Internal HTMX API - allows frontend to call backend parts without page loads
2. public API - json based allows customers or external apps to use our backend

For the public API we'll need a form of authentication; possibly JWT with API Keys rather than allowing direct user access.

More details will come shortly, if you'd like to help with this feature, please do add a comment below!

**Comment by amkarn258** [comment]
Hi @TreyWW ,

I would like to contribute on this. Can you please assign this to me?

**Comment by TreyWW** [comment]
You can help contribute but it won't be assigned to one person as it's a full revamp of pretty much everything. It'll need more discussions
