### ISSUE TITLE
bug: Forex API Down

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#410]
### What version of MyFinances are you currently using?

latest

### Describe the bug

Forex API [https://theforexapi.com/](https://theforexapi.com/) is currently down, and has been  for a while as shown by the [Issue (149)](https://github.com/MicroPyramid/forex-python/issues/149) on their github. We need an easier API alternative. Since what we need is so simple, we likely wont need a python dependency and will just need an API alternative.

If anyone would like to jump on this (ASAP) that would be appreciated. If not I can.

**Comment by kokoavailable** [comment]
i want to contribute to this project. what should i do ?

what do you think about this ?
https://currencylayer.com/

**Comment by amkarn258** [comment]
If no one is working on this, I can contribute. Can you please assign this to me?

**Comment by TreyWW** [comment]
Any update @amkarn258?

**Comment by fos9191** [comment]
Im happy to work on this if there is no other work being done. No problem if amkarn is working on it though.
