### ISSUE TITLE
bug: After logging in page is not fully loaded 

### ISSUE THREAD

**Issue by Domejko** [TreyWW/MyFinances#413]
### What version of MyFinances are you currently using?

v0.4.5

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

After logging in seams that page is not fully loaded, Dajngo debug toolbar is not visible, "Logged is as", and notifications as well, but profile picture is loaded and all invoices, clients etc are in place. When you press notification button all notifications are also there. You can swap to different tabs like Invoice, Clients and nothing change, only after refreshing whole page debug toolbar show up along with notifications and as who we are logged in.

Before refreshing the page:
![Screenshot from 2024-06-13 13-53-54](https://github.com/TreyWW/MyFinances/assets/119700507/9a9cb3b0-a456-46db-a962-6f039fc30bef)

After refreshing:
![Screenshot from 2024-06-13 13-57-28](https://github.com/TreyWW/MyFinances/assets/119700507/21ab78fe-63f5-462c-bf78-6e6808d306fb)

**Comment by TreyWW** [comment]
Related to #320

**Comment by Domejko** [comment]
> Related to #320

Ah sorry I was searching through topic but apparently wasn't searching good enough... You want me to delete this one or keep it due to some more details ?


I think that it's possible that in *backend/views/core/auth/login.py* 
```py
    try:
        resolve(next)
        response["HX-Location"] = next
    except Resolver404:
        response["HX-Location"] = "/dashboard/"

    return response
```
is not fully loading the page and that's why only after refreshing page when we get redirected through different function page is fully loaded and we are able to see everything. 

With some free time I will take a closer look on that.

**Comment by TreyWW** [comment]
Great catch! Yeah I'll close my issue, you've provided more details. I can assign you to this too and you have no rush to take a look at it. Appreciate it!

**Comment by TreyWW** [comment]
I have swapped HX-Location with HX-Redirect, this way everything is still HX-Boosted, the user notices nothing different, and all content is re-fetched this way. There's no content on the login page that would be useful anyways, so I feel this is a simple yet effective fix.
