### ISSUE TITLE
bug: Create account page button submit button shows "login" instead of "create"

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#432]
### What version of MyFinances are you currently using?

latest

### What device type are you currently facing the issue on?

Mobile, Desktop

### Describe the bug

![image](https://github.com/TreyWW/MyFinances/assets/73353716/2d7c8bbf-5810-40a9-b2b9-cccd88561d3f)

**Comment by fos9191** [comment]
I'll work on this

**Comment by TreyWW** [comment]
Merged in #433; thanks @fos9191!
