### ISSUE TITLE
idea: Clone invoice

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#458]
### How big is this feature?

Small

### Describe the problem

The ability to clone an invoice instead of typing all the details again

### Describe a possible solution

Bring up the create editor but pre-fill all of the existing details

**Comment by pvvramakrishnarao234** [comment]
I want to work on this idea. Are there any suggestions from where should I start with?

I have some doubts. For example,
if I were to clone a invoice and keep all the details same, the only thing that will be different is id or is there any other field that should be different from the original?

**Comment by TreyWW** [comment]
#Hey @pvvramakrishnarao234 appreciate the interest. The idea is that clone opens up the "create invoice" page with all of the fields pre-filled with the existing invoice ones. So no collisions will happen. You can use query params for pre filling values. E.g client=id 

Let me know if you have any other questions!
