### ISSUE TITLE
idea: remove HTMX from login screen

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#489]
### How big is this feature?

Small

### Describe the problem

At the moment our login page is just horrendous for UX. Slow, painful, cannot pre-fill..

Can just be a simple email and password, then add a loader to the button once pressed. 

### Describe a possible solution

- change to a one page rather than 2 step process
- add loader (hx-indicator) and disable the button while attempting login
- don't **require** htmx to login

**Comment by Yadu-M** [comment]
Hey, I'm new open source, can I try this. Thank you.

**Comment by TreyWW** [comment]
Hey @Yadu-M welcome along. Sure thing, have you got an estimate time of start? No big rush though, just would be good to know. Thanks!

**Comment by Yadu-M** [comment]
Estimate: I will start today. Will take 3 days at most. 

Questions
- Where can I get the loader for the button.
- Can you give me a brief explanation on "not requiring htmx".

Thanks.

**Comment by TreyWW** [comment]
You can use the view name from the {% url %} tag to get the view if that's what you mean. 

And to not require htmx would be to use a normal form and submit button and just add hx attributes on the button e.g disable. That way it should still login even if htmx somehow didn't load on the browser.

**Comment by Yadu-M** [comment]
> You can use the view name from the {% url %} tag to get the view if that's what you mean.

I meant the loader for the button when the user clicks login.

> And to not require htmx would be to use a normal form and submit button and just add hx attributes on the button e.g disable. That way it should still login even if htmx somehow didn't load on the browser.

Got it thanks.

**Comment by TreyWW** [comment]
Ah I see. I'll check the code as soon as I get home cause I'm not sure off the top of my head

**Comment by TreyWW** [comment]
So how we've done it on one of the other pages:

`form has hx-indicator='button[data-hx-loading="save"]'`

Button is
(main parts are "loading-htmx", "data-hx-loading", "loading-htmx-text" "loading-htmx-loader")
```html
<button class="btn btn-primary loading-htmx mt-4"
            data-hx-loading="save"
            type="submit">
        <span class="loading-htmx-text">Save</span>
        <span id="currency_save_loading"
              class="loading loading-spinner loading-htmx-loader"></span>
    </button> 
```

**Comment by TreyWW** [comment]
Btw `data-hx-loading="save"` can be anything, it's just used as a query selector lookup for the form to find the button. But I like to have it match, and prefix htmx queries with `data-hx-<type>="<item>"` kind of thing
