### ISSUE TITLE
bug: replace all API "Response()" with new "APIResponse()"

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#517]
### What version of MyFinances are you currently using?

latest

### Describe the bug

Replace all old public API responses from:

```py
    return Response({"success": True, "invoice_id": invoice.id}, status=status.HTTP_201_CREATED)
```

new:
```py
APIResponse(True, {"invoice_id": invoice.id})
```

**Comment by guninwasan** [comment]
Hey @TreyWW, can I work on this issue?

**Comment by TreyWW** [comment]
Hey @guninwasan of course, let me know if you need anything clarifying

**Comment by guninwasan** [comment]
hey @TreyWW, could you take a look at [this PR](https://github.com/TreyWW/MyFinances/pull/529)? Do let me know if there are any issues with it. Thanks!

**Comment by guninwasan** [comment]
hey @TreyWW, could you take a look at [this PR](https://github.com/TreyWW/MyFinances/pull/529)? Let me know if there are any issues with it. Thanks!

**Comment by guninwasan** [comment]
hey @TreyWW, can you take a look at [this PR](https://github.com/TreyWW/MyFinances/pull/529)? Let me know if I need to make any changes to it. Thanks!
