### ISSUE TITLE
[IDEA] Budgeting

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#7]
Set budget goals and categories (e.g., savings, investments, spending).
Compare actual expenses against budgeted amounts.
Receive alerts when approaching budget limits.

**Comment by Tianrui-Luo** [comment]
Hi @TreyWW, I'm sending this message on behalf of a group of 3 electrical and computer engineering students who want to contribute to your project, and we wonder if this task is still available or anyone else had already taken this task. If not, can you assign this task to us?

**Comment by TreyWW** [comment]
Hi there @Tianrui-Luo, unfortunately this feature isn’t yet ready to be added and needs more planning first. 
If you guys would like to help plan the feature before making it then sure thing.
I can provide more details tomorrow if you’re still interested. 

Thanks!

**Comment by HarryHuCodes** [comment]
> Hi there @Tianrui-Luo, unfortunately this feature isn’t yet ready to be added and needs more planning first. If you guys would like to help plan the feature before making it then sure thing. I can provide more details tomorrow if you’re still interested.
> 
> Thanks!

That will be great! 

To add to @Tianrui-Luo 's comment, this will be our first open source contribution. We came across this project and found it to be  interesting, active and full of opportunities. As students, the idea of a budgeting app appeals to us greatly. We hope to contribute in whatever way we can and gain experiences while doing so! Please let us know what we can help with. 

If you don't mind, is there a discord server that we can join to discuss further?

**Comment by TreyWW** [comment]
Hi @HarryHuCodes 

We do have a discord server, pretty much empty but like you say would be a lot easier to communicate in. 

https://discord.gg/P9jJQacu6S

Thanks for coming along, let me know how I can help you get started
