### ISSUE TITLE
[BUG] No services added text not added back to table when all items are deleted

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#71]
When removing all items from the  services table, the "no services added" text isnt there, but it should be
# Ref
![image](https://github.com/TreyWW/MyFinances/assets/73353716/9488db1e-a37b-4097-9fe5-317bf931ecf4)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/74084aef-5774-4b31-8105-e6c94ddb2200)
![image](https://github.com/TreyWW/MyFinances/assets/73353716/cf589c4d-261b-432a-a338-27866d8e7137)

**Comment by TreyWW** [comment]
Hi there @shinegit1,
Thanks for showing an interest, you have been assigned to the issue. Feel free to let me know you need any help, make a PR when you're finished.

Thanks again

**Comment by TreyWW** [comment]
Also, the page that this bug is on is `/dashboard/invoices/create/`, you will need an active server online to test that it works `127.0.0.1:8000` is our default, there are setup steps in `SETUP.md` (documentation/SETUP.md) which you could follow

**Comment by Crian69** [comment]
Has this issue been resolved? When I visit `/dashboard/invoices/create/` there is `No services added` in the table when there are no services.

**Comment by TreyWW** [comment]
So the issue is that when you add a service, then remove that so there is none, the text goes away. It should say no services when there aren't any

**Comment by TreyWW** [comment]
It's a very minor bug

**Comment by TreyWW** [comment]
Hi there @Crian69 & @shinegit1,

Any progress on this issue, would either of you like to work on it further?

**Comment by TreyWW** [comment]
Ah I see, thanks anyways @shinegit1. I'll give it a go later on if @Crian69 doesnt return. I'll post a comment explaining what I've done if I do figure it out

**Comment by TreyWW** [comment]
> I did a few things but they didn't work.

Ah i see why it was annyoing, so the `hx-delete` just does a post request, and doesn't return + swap new data. 

So I ended up using a htmx afterrequest event that uses javascript and checks if the rows.length == 0, then manually creates the "No services added" text. 

```js
document.addEventListener('htmx:afterRequest', function (event) {
    var container = document.getElementById('services_table_body');
    var rows = container.querySelectorAll('tr');
    if (rows.length === 0) {
        container.innerHTML = '<tr><td colspan="5">No services added</td></tr>';
    }
});
```

It's definitely not a nice solution, and generally I wouldn't creat annoying scripts like this, unless anyone else has any other solutions.

Commit: 1fc8c3142adea5cd67281a975c4575740f9be3bc
I'll leave this as a draft for now, and if there's no other comments i'll pull it in tomorrow.
