### ISSUE TITLE
[BUG] Move github actions dockerfile and dockercompose to /infrastructure/ folder

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#72]
I managed to get Actions working in root, so [docker-compose.ci.yml](https://github.com/TreyWW/MyFinances/blob/main/docker-compose.ci.yml) now works, as its in the same directory as requirements.txt. But I do want to move it back to `infrastructure/docker/`

Anyone able to help with these, leave a comment and we can talk more

**Comment by daavo03** [comment]
Hi there i'd like to give it a shot

**Comment by TreyWW** [comment]
Sure thing! Really appreciate your interest. You've been assigned

**Comment by TreyWW** [comment]
> Hi there i'd like to give it a shot

Hi @daavo03, any progress? Need any help?

**Comment by HessTaha** [comment]
Hi @TreyWW, can I contribute on this issue?

**Comment by HessTaha** [comment]
yes I'll give it a try ! 
And see afterward for docker step revamp

**Comment by HessTaha** [comment]
Hey, after some testing it appears a bit complicated to make it work as it is. Here are some proposals: 

1. Move the files to the infrastructure/backend, and add a "copy" step to the test workflow. The idea is to copy at least the docker-compose file to the root. 
2. Move only the Dockerfile and leave the docker-compose files at the root of the project. 
What  do you think ?

Links: 
[1](https://docs.docker.com/compose/compose-file/compose-file-v3/#context) || [2](https://stackoverflow.com/questions/68469150/setting-context-in-docker-compose-file-for-a-parent-folder)

**Comment by TreyWW** [comment]
Hey @HessTah, thanks for your research, much appreciated. 

Option 1 sounds like a great option. It's a bit of a shame that we'd need to use docker-compose `-f infrastructure/backend/` on every docker command. We may need to look into how others do it cause 3-4 extra files in root is quite extreme so there must be projects where they've moved it to a file but don't have to use -f on every command. 

Something to look into anyways, 

Thanks for the options though, 1 sounds good
