### ISSUE TITLE
[IDEA] Currency converter

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#84]
A page that allows the user to type in amounts, and select a currency and see the new amount. 

Also in the future maybe an option to preload the amounts from their balance, history, or graphs.

**Comment by Dkacurik** [comment]
HI,I'm willing to work on it.

**Comment by TreyWW** [comment]
Great! Thanks @Dkacurik for showing an interest. 

Let me know if you come into any issues or have any questions. Im always happy to help

**Comment by TreyWW** [comment]
Hi @Dkacurik,

Any progress on this feature, or do you need any help or anything? It's no rush, just checking to see if you're okay

**Comment by thaya-rk** [comment]
@TreyWW I'm intersted to work on this task

**Comment by TreyWW** [comment]
Sure thing @thaya-rk. You'll have to make sure @Dkacurik hasnt made any progress that isn't saved. But I'm okay if you both want to work on it. 

Thank you for showing an interest

**Comment by TreyWW** [comment]
👋 Any progress so far? Need any help?

**Comment by thaya-rk** [comment]
Hi @TreyWW ,
I'm facing an issue executing the code.By the way, how can I send you a dm to discuss this issue further?

**Comment by TreyWW** [comment]
> Hi @TreyWW ,
> 
> I'm facing an issue executing the code.By the way, how can I send you a dm to discuss this issue further?

Hi there @thaya-rk, really appreciate you messaging back. Do you have discord? If so you can dm me at "ospam". If you don't let me know if you have any other contact options or we can talk more here. Timezones may be a bit of a pain though.

**Comment by matthewjuarez1** [comment]
Has there been any progress on this issue? I'd like to contribute to this project, and this seems like a good start. If not, I'd love to help on whatever issues are currently at work

**Comment by TreyWW** [comment]
Hey @matthewjuarez1. I don't think there has been any progress so it's all yours. Let me know if you need any help getting started

**Comment by matthewjuarez1** [comment]
@TreyWW I was getting started tonight, but ran into some issues around the db when trying to set up. Could I dm you and work on a quick fix for this?

**Comment by TreyWW** [comment]
Sure thing, if you have discord my discord is `ospam`. But yeah I'm free to help

**Comment by mahasultan** [comment]
Hello @TreyWW, I'm interested in this issue, we're a group of university students and would love if you can assign this to us

**Comment by TreyWW** [comment]
Hi there @mahasultan. 

I'm so sorry I completely missed your comment. Sadly this feature was already assigned and has had progress. If there's any other features you'd like to work on let me know. We have some big ones that need some help so feel free to let me know
