### ISSUE TITLE
[Enhance] Need a new test for testing that a client gets returned (old test disabled)

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#85]
We need a new test to replace this, now i've moved the table loading to HTMX,
Our old test is 

```py
    def test_clients_check_clients_get_returned(self):
        self.client.login(username="user", password="user")
        # may need this
        #headers = {
        #    "HTTP_HX-request": "true",
        #}
        response = self.client.get(reverse("clients dashboard")) # may need this too, **headers)
        amount_of_clients_returned = len(response.context["clients"])
        self.assertEqual(amount_of_clients_returned, 0)

        Client.objects.create(
            name="bob smith",
            user=response.wsgi_request.user,
        )

        response = self.client.get(reverse("clients dashboard"))
        amount_of_clients_returned = len(response.context["clients"])
        self.assertEqual(amount_of_clients_returned, 1)
```

The file is `backend/tests/views/test_clients.py`

So pretty much, the test checks how many clients get returned before + after you create a client to make sure the for loop works. But now we use HTMX to get the returned data seperately, the variable "clients" isnt passed into the page. 

If anyone would like to work on this, leave a comment below. I could help explain more, but not sure how to actually achieve the logic. Thanks

**Comment by bermr** [comment]
Hi. I testes and the test is passing with the code commented: https://github.com/TreyWW/MyFinances/pull/92, but I had to change one line in `models.py`.

@TreyWW can you have a look?
