### ISSUE TITLE
[Enhance] We need MORE TESTS

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#86]
Along with #85 we need some tests for all of the new pages i've recently created.

Also needs tests for the returned data from things like receipts, invoices etc.

One test (#85) will kind of be a template for the rest of them, but i'd appreciate any help

**Comment by phatboislym** [comment]
hello, I'd like to take a shot at this

**Comment by flyingdev** [comment]
Hi, @TreyWW 

I created pull request against this issue. could you review?

thank you.

**Comment by TreyWW** [comment]
Thank you @flyingdev, they were some amazing tests. I really appreciate that, thank you man.

**Comment by flyingdev** [comment]
Thank you @TreyWW 
I love to contribute more.

**Comment by TreyWW** [comment]
That's great, I'm trying to keep this project active as much as possible. Feel free to create new issues for ideas, prs for bugs or comment on any issues you think sound manageable. Don't feel like you have to contribute though, but it is really appreciated

**Comment by flyingdev** [comment]
I am interested in personal finance app as well. Will do certainly.  Thank
you.

**Comment by TreyWW** [comment]
It's amazing that you're a Self-Employed dev, we hardly ever see them and it's so so inspiring. Yeah I started this for myself as I've started to get clients recently too, and I thought it's a good opportunity to get other devs an opportunity to work on something they might like to use too
