### ISSUE TITLE
[IDEA] Teams

### ISSUE THREAD

**Issue by TreyWW** [TreyWW/MyFinances#87]
Teams have been implemented slightly, you can now `create` a team, `invite` users to your team, `leave` a team etc
We now need the `core` functionality of teams, this kind of functionality would include: switching modes between "individual" and "team" mode, when in team mode you make actions on behalf of your team.

When you create actions, the thing like lets say `Creating a client`, the client would be assigned to the team rather than you, and in the team there would be a `log` of this action. (obviously you'd need permission [another issue im about to make] to do this)

## What areas does this idea come under? 
- Frontend 
- Backend 
- Test Cases

Please add a comment below if you would like to help improve this feature, thanks

**Comment by phatboislym** [comment]
please ignore, just seen that I commented on the wrong issue

**Comment by TreyWW** [comment]
> please ignore, just seen that I commented on the wrong issue

hi @phatboislym, did you still want to work on this issue?

**Comment by phatboislym** [comment]
no, wanted to work on another issue

**Comment by sir-temi** [comment]
Hi @TreyWW, this sounds interesting and would love to work on this.

**Comment by TreyWW** [comment]
Hi there, sure thing. Really appreciate the interest. Let me know if you need any details or help getting started. I'll be on tomorrow morning :)

**Comment by sir-temi** [comment]
Cool man. Yes more details about the design you have in mind will be nice.

**Comment by TreyWW** [comment]
Sorry, didnt have enough time to get back to you yesterday.
So this feature is less to do with design and more to do with structure and model concept.

We kind of just need a plan of how we're going to store things like receipts and clients but instead of a foreign key to a user, it'll be to the team. And then a way of swapping between your Team, and your Individuals account.

Design wise it'll just be an option when you click on your profile picture to "Swap Account" between your Individual account and Team account. That dropdown wouldn't take 2 minutes so that's fine.

Just yeah, more of an idea and backend structure of how we're going to add the Individual/Team option for every feature so far

**Comment by sir-temi** [comment]
Thanks for the response! To clarify my earlier mention of 'design,' I'm specifically focused on the features' underlying structure and interactions. For instance, I'm keen on understanding your design idea of how the system will differentiate actions in 'individual' and 'team' modes, and how actions like creating a client will be logged under the team. This pre-coding design phase is crucial, that was why I asked if you already have a design concept for these aspects in mind

**Comment by TreyWW** [comment]
Apologies for my misunderstanding. Yeah I see, especially for big features like this a well working and thought out structure would be essential. 

I've not yet came up with a finished structure or idea. I've got a few thoughts of how parts may work but the underlying system design needs more thinking. 

Things like: storing team/individual status via session or in database, would we do if statements in every view for determining if they're doing it for themself or others (would need a lot of permission checks to), or would we have duplicated models for teams and separate urls. 

Yeah I've not had any ideas really, it's a big feature I've not had any thought on how to even start thinking about it. 

Thanks again, any help is appreciated

**Comment by sir-temi** [comment]
Okay great man, I can start working on it by weekend.

**Comment by TreyWW** [comment]
Hey, as for the mixins, we don't use class based views, they're all function based. In general our views are small as we don't have many features out yet, but still needs a bit of a clean up.

I'm not sure what there is in replace of mixins for this use case, only thing I could think of is a decorator, not sure how that functionality would help though. 

But yeah just thought i'd let you know, appreciate the response. Sorry I replied so late

**Comment by sir-temi** [comment]
Hey, so sorry for the late response. When will you be online for so we can conclude on somethings?

**Comment by TreyWW** [comment]
I'll likely be online on the weekend. If you'd prefer a more live chat like on discord then let me know

**Comment by sir-temi** [comment]
Okay cool. Please send your discord username.

**Comment by TreyWW** [comment]
Sorry, completely missed that message. `ospam`

**Comment by TreyWW** [comment]
Any progress on this, a ETA of when this could be worked on? It's holding the app back quite a lot to be fair @sir-temi
