### ISSUE TITLE
Add favicon and other icon options plus make My Finances button usable

### ISSUE THREAD

**Issue by PhilipZara** [TreyWW/MyFinances#96]
Hello everyone! I am new here and I would love to contribute to this project. The suggestions I propose are very basic. I have already created a favicon and made the My Finance button on the left upper corner usable returning to the dashboard. What are the steps from my end to show my suggestions? Do I create first an issue and then a PR? Are there any specific criteria I must meet first?

I really appreciate any help you can provide.

## Preconditions:
Past issue has finished to allow blah blah

## Acceptance Criteria:
- Please do task a
- Please do task b

## Definition of Done:
- [ ] Created tests/urls logged_in and unlogged_in json objects for any added URLS
- [ ] Created tests/views for any added VIEWS
- [ ✅] Code has been tested with `python manage.py test backend`
- [ ] All of Acceptance Criteria is complete

**Comment by TreyWW** [comment]
Hi there @PhilipZara, yeah you can create an issue for any ideas, features or questions. You can make one issue per idea too. Then after it's done create a PR to get it merged in. I'm happy to provide any help you need, feel free to ask questions!

Thanks for showing your interest

**Comment by TreyWW** [comment]
But as for the favicon and icon changes feel free to make a Pull request and write your changes and show screenshots etc in there. Any changes will be asked in there

**Comment by PhilipZara** [comment]
Hello @TreyWW thanks for welcoming me and for the help! 

On my PR I have included a picture of how the favicon looks. But, from this point forward for any design changes, I will create a separate PR.
